### ISSUE TITLE
reads2bins.py – missing 'format' issue

### ISSUE THREAD

**Issue by harfeorth** [anuradhawick/MetaBCC-LR#11]
Dear Anuradha,
I am very interested in the approach used by metabcc-lr. I've successfully generated bins etc, but I'm not good with python and hit an issue when running bin splitting script, reads2bins.py

Traceback (most recent call last):
  File "/opt/miniconda/envs/pacbio_mag/MetaBCC-LR/reads2bins.py", line 29, in <module>
    for record, bin_id in zip(SeqIO.parse(readsPath), open(readBinsPath)):
TypeError: parse() missing 1 required positional argument: 'format'

Does 'format' here refer to the data input – Fasta or Fastq (my data is fastq), as the variable 'readsType' is defined above (line 17-20) but is not feed into the SeqIO output. Is something missing from the script??

Regards and thank you for developing,
David

**Comment by anuradhawick** [comment]
Dear Dr Green (@harfeorth),

Thanks a lot for raising this issue. I have missed this detail and it is fixed now. I do apologise for the inconvenience.

Please feel free to get in touch if you need any assistance tuning parameters, seeing plots, etc. Few remarks;

* visualised bin plots are available in `images`.
* use `--resume` with varying sensitivity to change the level of bin fragmentation.
* changing embedding with `--embedding` parameter (as tsne, umap or song) can help bin different datasets.

Kind regards
Anuradha

**Comment by anuradhawick** [comment]
The issue has been fixed in 872dc85b36e89c910445ef34388c04c7ddcf634b

**Comment by harfeorth** [comment]
Dear Anuradha,

Thank you so much for the speedy changes. I've just run this and it's worked perfectly!

Yes, I do want to look at the tuning parameters: in addition to trying different embedding parameters, would you recommend testing the --k-size and --sensitivity settings as the main other parameters to change?

All the best,
David

________________________________

**Comment by anuradhawick** [comment]
Dear Dr Green (@harfeorth),

`--k-size` and `--sensitivity` indeed effects the results. Ideally, you should expect better results at a higher `k-size` (4 to 5) on more accurate reads (CCS or HiFi). But it might need a little bit more memory. The sensitivity parameter determines how well the clusters are separated. Higher sensitivity, higher fragmentation plus more bins and vice-versa.

I have just fixed a bug on `--resume` feature and kindly get a `git pull` before you proceed.

I am also planning to improve this tool with more robust clustering and will give an update here.

P.S.

Our latest work [LRBinner](https://github.com/anuradhawick/LRBinner) (Accepted at [WABI 2021](http://www.acm-bcb.org/WABI/2021/)) works out on these parameter limitations. The code is being refactored (still it should work fine) in the coming few days and will be ready for you to test if that is interesting.

Best regards,
Anuradha
