### ISSUE TITLE
There are some questions about MetaBCC-LR that I would like to consult you

### ISSUE THREAD

**Issue by Bioinformations** [anuradhawick/MetaBCC-LR#12]
Hello，I have difficulty using this software. when i execute this command : ”python mbcclr --resume -r test_data/data/reads.fasta -g test_data/data/ids.txt -o test_output -e umap -c 25000 -bs 10 -bc 10 -k 4“，I don't know about how the parameter g is taken. Is it feasible to use ids.txt files in the test data? Hope to be able to get your help ！

**Comment by anuradhawick** [comment]
You don’t need to use `-g`. Please run program without that.

**Comment by Bioinformations** [comment]
I can run this program now, thank you very much for your help !

**Comment by anuradhawick** [comment]
Wonderful. 
cheers,
Anuradha
