### ISSUE TITLE
MetaBCC-LR cannot locate the output folder (FileNotFoundError: [Errno 2] No such file or directory: 'metaBCCLR_default_params_output/misc/filtered_reads.fasta')

### ISSUE THREAD

**Issue by hdore** [anuradhawick/MetaBCC-LR#3]
Hello,

Thank you for this tool, I can't wait to see the result on my Nanopore dataset. It is currently running :)
I just wanted to report a "bug": I got the following error a few minutes after launching the job:
FileNotFoundError: [Errno 2] No such file or directory: 'metaBCCLR_default_params_output/misc/filtered_reads.fasta'

I figured that it was because the folder "metaBCCLR_default_params_output" that I put in the --output argument already existed before I launched MetBCC-LR.
I think this might be because of this part of the MetaBCC-LR script:
if not os.path.exists(output):
        os.makedirs(output)
        os.makedirs(f"{output}/images")
        os.makedirs(f"{output}/misc")

Since the last 2 lines are included in the if loop, the folders "images" and "misc" are not created when the output folder already exists, hence the error.

I hope this can help others!

Hugo

**Comment by anuradhawick** [comment]
Thank you very much for catching this bug. We will fix this soon.

Please let us know the expectation-performance gap. We are working on a second version and would love to have some input. 

Best regards
Anuradha

**Comment by hdore** [comment]
Thank you!
I also had trouble with the installation because of my gcc version (and probably also the g++ version, but it's not listed as a dependency so I'm not sure).

I just ran into another error while tuning sensitivity but I'll open a different issue for an easier tracking.

Best,

Hugo

**Comment by anuradhawick** [comment]
Thanks for the suggestions and comments. Much appreciated. We will attend them soon.

Best regards
Anuradha
