### ISSUE TITLE
line 76 error

### ISSUE THREAD

**Issue by sankadinesh** [anuradhawick/MetaBCC-LR#7]
Hi there,
How to resolve the following error while running ./MetaBCC-LR

./MetaBCC-LR 
  File "./MetaBCC-LR", line 76
    checkpoints_path = f"{output}/checkpoints"
                                             ^
SyntaxError: invalid syntax

Regards,
Dinesh

**Comment by anuradhawick** [comment]
Hello,

Can you confirm whether you are running pythong version 3.7 or above? It might have been the issue. Older python versions did not support template strings.

**Comment by sankadinesh** [comment]
Hi there, 
yes. I have confirmed it. I am [attaching](url) screen shot as well. Pls check. Thanks 
Regards,
Dinesh S L 

![Screenshot 2020-12-20 at 3 12 14 AM](https://user-images.githubusercontent.com/43870684/102700211-8250c080-4271-11eb-9c74-23db391a52cb.png)

**Comment by anuradhawick** [comment]
Hi,

You must be using a python version older than 3.6. As other users haven't got the error could you try following and see if it is 3.7?

`python --version `

**Comment by sankadinesh** [comment]
Hi Anuradha, 
yes. it is 3.7
Thanks 
Regards,
Dinesh S L
![Screenshot 2020-12-20 at 3 24 56 AM](https://user-images.githubusercontent.com/43870684/102700426-3868da00-4273-11eb-8b04-d397eebd5ad7.png)

**Comment by anuradhawick** [comment]
Hi Dinesh,

It's strange and I'll have a deeper look as soon as I return to uni after holiday shutdown. 

Thanks for understanding
Anuradha

**Comment by anuradhawick** [comment]
Could you try to run the program without installing it? Although you might have python3 the version caught by the main python file's header may be different.

You can build using `build.sh` and then run using `python3 MetaBCC-LR` from the cloned directory.
