### ISSUE TITLE
Need to mkdir "misc" and "images" before running?

### ISSUE THREAD

**Issue by dinhe878** [anuradhawick/MetaBCC-LR#9]
Hi,

Thanks for developing this great tool. I found something a bit strange that I think python-related:

> 2021-05-21 11:27:18,941 - INFO - Filtering reads
> Traceback (most recent call last):
>   File "/services/tools/anaconda3/4.4.0/bin/MetaBCC-LR", line 201, in <module>
>     main()
>   File "/services/tools/anaconda3/4.4.0/bin/MetaBCC-LR", line 144, in main
>     runners_utils.run_filter(reads_path, output, ground_truth)
>   File "/home/people/dinghe/.local/lib/python3.6/site-packages/mbcclr_utils/runners_utils.py", line 25, in run_filter
>     output_fasta_file = open(f"{output}/misc/filtered_reads.fasta", "w+")
> FileNotFoundError: [Errno 2] No such file or directory: './misc/filtered_reads.fasta'

I am not sure which python version has `open(f"{output}/misc/filtered_reads.fasta", "w+")` that can create a file along with non-existing folder. But al least python3.6 does not have this option. The processes worked fine after creating two folders "misc" and "images".

Also, I wonder if there's an option where all the fastq-bins can be created, i.e. each bins will have a fastq file, that would be great for downstream processes.

Best, Ding

**Comment by anuradhawick** [comment]
Hello,

Thanks for raising this bug. This must be a bug is the recent push. I will fix this and get back to you soon. There are few more planned updates too. Will let you know. I will keep the issue open for until it is fixed. 

Best regards
Anuradha

**Comment by anuradhawick** [comment]
@dinhe878 I have fixed the issue and a brand new version of the tool is available. Please clone the repo again and use it. Refer to the updated Readme too. I hope this update will improve results. I will update the repo again with many more improvements. :)

You might need to install SONG-vis and UMAP for this version to run. Use the following codes;

```
pip install umap-learn
pip install song-vis
```

Code to separate fastq files is available [here](https://github.com/anuradhawick/MetaBCC-LR/issues/2#issuecomment-711450643). There will be several updates and we will include this script in the program itself in next update (soon).

So I will close this issue.

Thanks
Anuradha
